name: Node.js CI

on:
  workflow_call:
    inputs:
      lint:
        required: false
        type: boolean
        default: true


jobs:
  node_ci:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Lint
        if: ${{ inputs.lint }}
        run: npm run lint
      - name: Run tests
        run: npm run test
